_episodes/02-project-setup.md: Improving challenge.
brownsarahm/python-data-project pull request #81
Opened 2021-05-26 17:57 UTC by vinisalazar

Hi,

This is related to #55.

Summary of changes:
  - Renames challenge from 'Exercise' to 'Creating project files'.
  - Adds 'mkdir results' command.
  - Improves explanation of .gitignore.

Best,
Vini

2021-05-27 21:47 UTC, brownsarahm requested changes

2021-05-27 21:47 UTC, brownsarahm commented on _episodes/02-project-setup.md
> +> touch __/.gitignore # flags files that should be ignored by version control, such as big data files
I don't like adding this to the exercise. this becomes a question about how git works.

2021-05-27 21:47 UTC, brownsarahm commented on _episodes/02-project-setup.md
> +> > how to download the data.
Lets put all of the talk about gitignore in its own section.

2021-05-27 21:49 UTC, brownsarahm commented
This doesn't really address #55 though; this improves gitignore, but doesn't add advice about how to work with data and results very much.

2021-05-31 14:38 UTC, vinisalazar commented
Thanks for the review, @brownsarahm. I've updated this branch with a couple of commits that improve the explanation of `.gitignore` and also add a callout block of where to place results.

2025-10-01 12:00 UTC, merged